feat: fine-grain resource config at skeleton level
defenseunicorns/leapfrog-model-skeleton pull request #13
Opened 2024-02-02 20:48 UTC by justinthelaw

- Add README details
- Moved GPU, CPU, and Memoray resource control to skeleton
- GPU enablement and resources always prompted

2024-02-07 18:55 UTC, YrrepNoj commented on chart/values.yaml
>  securityContext: {}
```suggestion
securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
```

2024-02-07 21:55 UTC, YrrepNoj commented on zarf.yaml
> +    prompt: true
Here and below; Can we remove the `prompt: true`?

As we start adopting more UDS patterns we are going to move away from Zarf variables and want to start moving away from prompting/expecting them.

2024-02-08 07:41 UTC, YrrepNoj requested changes

2024-02-08 15:08 UTC, justinthelaw commented on zarf.yaml
> +    prompt: true
Yessir! Also removed form the REQUESTS and LIMITS

2024-02-08 15:10 UTC, justinthelaw commented on zarf.yaml
> +  version: 0.5.0
I like that! Done

2024-02-08 17:02 UTC, YrrepNoj approved these changes

2024-02-08 17:21 UTC, merged